server:
  port: 8002 # 注册中心占用8080端口
spring:
  profiles: slave1

  application:
    name: yunzai-reg
eureka:
  instance:
    hostname: slave1
    preferIpAddress: true
    enableSelfPreservation: false
    leaseRenewalIntervalInSeconds: 2
#    environment: devp
  client:
    registerWithEureka: true
    fetchRegistry: true

    serviceUrl:
      defaultZone: http://xucheng:123@master:8001/eureka/,http://xucheng:123@slave2:8003/eureka/   #其实就是 http://localhost:8080/eureka/
security:
  basic:
    enabled: true
  user:
    name: xucheng
    password: 123